apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
          - name: DB_PASSWORD
            value: "PASS"
          - name: DB_USERNAME
            value: "TESTUSER"
          - name:  DB_DATABASE
            value: "KUBE-NEWS"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      nodePort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testedp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testedp
  template:
    metadata:
      labels:
        app: testedp
    spec:
      containers:
        - name: kubenews
          image: IMAGE #fabricioveronez/kube-news:v2
          env: 
          - name: DB_DATABASE
            value: "KUBE-NEWS"
          - name: DB_USERNAME
            value: "TESTUSER"
          - name: DB_PASSWORD
            value: "PASS"
          - name: DB_HOST
            value: "postgre"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-news 
spec:
  selector:
    app: kubenews
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000 
  type: LoadBalancer
